env:
  EM_VERSION: 3.1.61
  EM_CACHE_FOLDER: 'emsdk-cache'

name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v14
      with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      
    - name: Checkout raylib
      uses: actions/checkout@v4
      with:
         repository: 'raysan5/raylib'
         path: raylib
       
    - name: Check EMSDK version and compile raylib for web
      run: |
        emcc --version
        cd ./raylib/src
        make EMSDK_PATH=${{ env.EMSDK }} PLATFORM=PLATFORM_WEB -B
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build project
      run: |
        source ${{env.EMSDK}}/emsdk_env.sh
        make PLATFORM=PLATFORM_WEB -B #TODO ADD PASSING PATHS TO THIS
      shell: bash
