env:
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: 'emsdk-cache'

name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v14
      with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

    #TODO Add compile and install raylib (for web) job 
    - name: Checkout raylib
      uses: actions/checkout@v4
      with:
         repository: 'raysan5/raylib'
       
    - name: Compile raylib for web
      run: |
        source emsdk/emsdk_env.sh
        cd raylib
        sudo make PLATFORM=PLATFORM_WEB -B
      shell: bash

    - name: Build project
      run: |
        source emsdk/emsdk_env.sh
        make PLATFORM=PLATFORM_WEB -B #TODO ADD PASSING PATHS TO THIS
      shell: bash

   # - name: Deploy to GitHub Pages
      #uses: peaceiris/actions-gh-pages@v3
      #with:
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        #publish_dir: ./  # Directory to deploy (make sure it contains index.html and other necessary files)
