env:
  EM_VERSION: 3.1.61
  EM_CACHE_FOLDER: 'emsdk-cache'

name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v14
      with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      
    - name: Checkout raylib
      uses: actions/checkout@v4
      with:
         repository: 'raysan5/raylib'
         path: raylib
       
    - name: Check EMSDK version and compile raylib for web
      run: |
        emcc --version
        cd ./raylib/src
        make EMSDK_PATH=${{ env.EMSDK }} PLATFORM=PLATFORM_WEB -B
        sudo make install
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: boids
    
    - name: Build project
      run: |
        cd boids
        source ${{ env.EMSDK }}/emsdk_env.sh
        emcc --version
        ls ..
        make EMSDK_PATH=${{ env.EMSDK }} RAYLIB_PATH=../raylib PLATFORM=PLATFORM_WEB -B #TODO ADD PASSING RAYLIB AND PYTHON PATHS TO THIS
      shell: bash

    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: whereami
      run: |
        pwd
        ls -l
        
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: boids
        path: ./boids/target/web
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write
      pages: write

    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: boids
        
        
      
    
      
